export const SOURCE_UPDATE = 'SOURCE_UPDATE';
export const ERROR_UPDATE = 'ERROR_UPDATE';
export const OPTIONS_UPDATE = 'OPTIONS_UPDATE';
export const UI_OPTIONS_UPDATE = 'UI_OPTIONS_UPDATE';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
